### ISSUE TITLE
You could use sync.Map to replace SafeSeenHosts entirely ...

### ISSUE THREAD

**Issue by CaledoniaProject** [assetnote/surf#2]
I read about your journal on BSides, and I came to this repo. 
1. I think you could add more description somewhere in this repo, I couldn't understand surf before reading the source code
2. You could use sync.Map to replace SafeSeenHosts entirely, your logic is simple and there's no need to use a mutex yourself.

**Comment by infosec-au** [comment]
hey thanks, appreciate the feedback, ill see if i can refactor this in the future.

this code was written quite quickly when it was needed for a live hacking event, but hasn't been iterated on since then. it led to a lot of success, and worked really well! i really hope it helps you the next time you're exploiting an ssrf.
